/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#adc7f8',
        'outline-variant': '#c4c6d0',
        'secondary-fixed-dim': '#ffb785',
        'on-secondary-fixed-variant': '#723700',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'surface-container-lowest': '#ffffff',
        surface: '#f8f9ff',
        'on-surface': '#0b1c30',
        'on-primary-fixed-variant': '#2c4771',
        'on-primary-fixed': '#001b3d',
        'on-background': '#0b1c30',
        'secondary-container': '#fd8100',
        'on-primary': '#ffffff',
        'on-primary-container': '#718bb9',
        primary: '#000e24',
        'surface-container': '#e5eeff',
        'primary-container': '#00234b',
        'tertiary-fixed-dim': '#c3c7ca',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ffdcc6',
        'surface-container-high': '#dce9ff',
        'on-secondary-fixed': '#301400',
        'surface-dim': '#cbdbf5',
        tertiary: '#0a0e11',
        outline: '#74777f',
        'on-tertiary-fixed-variant': '#43474a',
        'on-secondary-container': '#5d2c00',
        'inverse-primary': '#adc7f8',
        'inverse-on-surface': '#eaf1ff',
        'tertiary-container': '#202426',
        'inverse-surface': '#213145',
        'surface-variant': '#d3e4fe',
        'on-tertiary-container': '#878b8e',
        'surface-tint': '#455f8a',
        secondary: '#954a00',
        'on-error': '#ffffff',
        'on-surface-variant': '#43474e',
        'on-tertiary-fixed': '#181c1e',
        'on-secondary': '#ffffff',
        'surface-bright': '#f8f9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        background: '#f8f9ff',
        error: '#ba1a1a',
        'tertiary-fixed': '#e0e3e6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '40px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        base: '4px',
        gutter: '20px',
        sm: '8px',
        xs: '4px',
        lg: '24px',
        md: '16px',
      },
      fontFamily: {
        'headline-md': ['Anybody'],
        'body-sm': ['Work Sans'],
        'label-bold': ['Work Sans'],
        'headline-lg': ['Anybody'],
        'body-lg': ['Work Sans'],
        'body-md': ['Work Sans'],
        'display-lg': ['Anybody'],
        'headline-lg-mobile': ['Anybody'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': [
          '14px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
